### ISSUE TITLE
Do not copy Xml comments for partial classes

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#10]
As classes are partial, the XML comments on partial class definitions are not necessary.

**Comment by maca88** [comment]
Should we use the `content` tag explained [here](http://stylecop.soyuz5.com/SA1601.html)?

**Comment by hazzik** [comment]
I think yes, something like `<conent>Contains generated async methods</content>`*. 
--
*Spelling should be fixed

**Comment by maca88** [comment]
Now the content tag is added for each generated type

**Comment by hazzik** [comment]
Thanks
