### ISSUE TITLE
Invalid required CancellationToken on methods with default values

### ISSUE THREAD

**Issue by fredericDelaporte** [maca88/AsyncGenerator#115]
When  the `CancellationToken` parameter is set as required, it may be added after an optional parameter while not being itself optional, which is invalid.

By example:
```c#
public void Do(bool reallyDo = true)
{
    ...
}
```

Generated:
```c#
public Task DoAsync(bool reallyDo = true, CancellationToken cancellationToken)
{
    ...
}
```

Either the `cancellationToken` required property should be overridden to optional in such case, or it should be put before the first optional parameter.

**Comment by maca88** [comment]
Fixed by changing `cancellationToken` parameter from required to optional.
