### ISSUE TITLE
Throws for iterator returning non generic IEnumerable

### ISSUE THREAD

**Issue by bahusoid** [maca88/AsyncGenerator#119]
If you modify the following method:
https://github.com/nhibernate/nhibernate-core/blob/109f0853bcc6751136e8fe03eac379c7d5765b18/src/NHibernate/Engine/Query/HQLQueryPlan.cs#L153-L175

in the following way:
``` C#
public IEnumerable PerformIterate(QueryParameters queryParameters, IEventSource session)
{
	foreach (var t in Translators)
	{
		foreach (object obj in t.GetEnumerable(queryParameters, session))
		{
			yield return obj;
		}
	}
}
```
Async generator throws attached exception:
[Excepton.txt](https://github.com/maca88/AsyncGenerator/files/2896645/Excepton.txt)

**Comment by hazzik** [comment]
This code cannot have async representation. See #94.

**Comment by bahusoid** [comment]
For IEnumerable<object> it generates code similar to the following:
```C#
private async Task<IEnumerable<object>> GetEnumerableAsync(QueryParameters queryParameters, IEventSource session, CancellationToken cancellationToken)
{
	cancellationToken.ThrowIfCancellationRequested();
	var yields = new List<object>();
	foreach (var t in Translators)
	{
		foreach (object obj in await (t.GetEnumerableAsync(queryParameters, session, cancellationToken)).ConfigureAwait(false))
		{
	yields.Add(obj);
		}
	}
	return yields;
}
```

Anyway this issue not about async representations - now async generator unexpectedly quits with above exception.
