### ISSUE TITLE
Does not work with VS 2019

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#122]
[exec] 13:12:57,598 INFO  CommandLine:0 - AsyncGenerator
     [exec]
     [exec] 13:12:57,955 INFO  AsyncCodeGenerator:0 - Generating async code started
     [exec] 13:12:58,268 FATAL CommandLine:0 - System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
     [exec]    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
     [exec]    at System.Reflection.RuntimeAssembly.get_DefinedTypes()
     [exec]    at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
     [exec]    at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
     [exec]    at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
     [exec]    at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
     [exec]    at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
     [exec]    at Microsoft.CodeAnalysis.Host.Mef.DesktopMefHostServices.get_DefaultServices()
     [exec]    at AsyncGenerator.AsyncCodeGenerator.CreateWorkspace(String targetFramework)
     [exec]    at AsyncGenerator.AsyncCodeGenerator.<GenerateAsync>d__0.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at AsyncGenerator.CommandLine.Program.Main(String[] args)

**Comment by maca88** [comment]
Version `0.13.3` is published, try if it works also for you.

**Comment by bahusoid** [comment]
Can you also make this fix in 0.8 version (which is used by NHibernate 5.2)?

**Comment by fredericDelaporte** [comment]
I have not updated my personal VS and so should still be able to regenerate the 5.2 branch if needed, just let me know. (Preferably by direct email if you have it, since I am currently not very active...)

**Comment by maca88** [comment]
The fix is now released also in `0.8.2.11` version.
