### ISSUE TITLE
Searching async counterparts in inherited types

### ISSUE THREAD

**Issue by maca88** [maca88/AsyncGenerator#13]

**Comment by fredericDelaporte** [comment]
Is this for cases like this [class](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate.Test/Insertordering/InsertOrderingFixture.cs#L534) in NHibernate? The `StatsBatcher` class override synchronous methods for computing some stats. The async overrides of async counterparts are not generated, causing it to not compute stats in async cases.

I am fixing this manually, but it would be great if it was possible to generate async counterparts of overridden synchronous methods.

**Comment by maca88** [comment]
No, because the async counterpart of the called method `PrepareBatchCommand` from `AbstractBatcher` is also defined in `AbstractBatcher`. What you discovered is actually a kind of bug as for this case the generator should generate the async counterpart for the overriden method as we want the same behaviour for the sync and async method. I've opened a bug [here](https://github.com/maca88/AsyncGenerator/issues/46).

**Comment by maca88** [comment]
The bug is now fixed so for the current NHibernate code (master branch) the only missing override that gets generated is `DebugConnectionProvider.GetConnectionAsync`.
