### ISSUE TITLE
Support C# 8 nullables

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#134]
The `<auto-generated>` resets the `#nullable` flag (disables it), so the generator should emit `#nullable restore` at the top of the generated file (after the `/// <auto-generated>`) to restore the flag to project's default settings. Otherwise the code could become not compilable.

**Comment by hazzik** [comment]
> @maca88 added the bug label
Not a bug per se.

**Comment by hazzik** [comment]
Also, this, probably, needs to be controlled by an option, because on older compilers this directive could lead to errors.

**Comment by maca88** [comment]
> Not a bug per se.

Changed to enhancement.

> this, probably, needs to be controlled by an option

#134 checks the `Nullable` tag in csproj. The mentioned PR does not work when using .NET 4.6.1 as the API for checking nullables is not available.
