### ISSUE TITLE
NUnit: Support fluent (Assert.That) assertions 

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#17]
`Assert.That`'s async counterpart is ....

... `Assert.That`

Minor.

**Comment by maca88** [comment]
Didn't know that :)... this special case can be supported by adding a custom [async counterpart finder](https://github.com/maca88/AsyncGenerator/blob/master/Source/AsyncGenerator.Tests/ExternalProjects/NHibernate/NUnitAsyncCountepartFinder.cs#L11).

**Comment by hazzik** [comment]
>this special case can be supported by adding a custom async counterpart finder.

Yeah, I was trying to do it myself but did not have enough knowledge how to implement it.
