### ISSUE TITLE
Generalize NUnit support as a plugin

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#26]
There is an NUnitAsyncCountepartFinder and various conversion methods for better tests generation. I think this can be generalized as a plugin.

Minor

**Comment by maca88** [comment]
`NUnitAsyncCountepartFinder` is [now](https://github.com/maca88/AsyncGenerator/commit/64a34bb9da73444fe32be1fd3007a47c45f799bc) a built-in plugin. Also, there is no need to write a custom plugin for async extension methods like  `LinqAsyncCounterpartsFinder` as now we have [AsyncExtensionMethods](https://github.com/maca88/AsyncGenerator/blob/master/Source/AsyncGenerator.Core/Configuration/IFluentProjectAnalyzeConfiguration.cs#L77) option where we can register our extension method inside a project.
