### ISSUE TITLE
Generate methods with CancellationToken argument

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#3]

**Comment by maca88** [comment]
Interesting idea, I will add it to my todo list.

**Comment by hazzik** [comment]
Fixed in master

**Comment by hazzik** [comment]
Actually, I think one thing is missing. We might want to have generated the cancellation exception in front of the method body if the token was cancelled.

**Comment by maca88** [comment]
I agree with you but here we need to be very carefully as this logic may cause some unwanted behaviors. Lets see an example:
Original code
```
public void MyMethod() {
    var stream = new MemoryStream();
    ....
    SubMethod();
    stream.Dispose();
}

public void SubMethod() { // An empty method that will be forced to be converted because of some inheritance dependency
}
```
Converted:
```
public async Task MyMethodAsync(CancellationToken cancellationToken = default(CancellationToken)) {
    cancellationToken.ThrowIfCancellationRequested();
    var stream = new MemoryStream();
    ....
    await SubMethodAsync(cancellationToken); // The original code supposed that this method would never throw
    stream.Dispose();
}

public Task SubMethodAsync(CancellationToken cancellationToken = default(CancellationToken)) {
    if(cancellationToken.IsCancellationRequested) {
        return Task.FromCanceled<string>(cancellationToken); // If we got here then the stream that was allocated will never be disposed!
    }
    return Task.CompletedTask;
}
```
I know that the above example is an example of a badly written code but we still need to consider this case.

So let see how this logic shall be implemented for various cases (inspired by Microsoft [here](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/File.cs#L946) and [here](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/File.cs#L973)):
```
// Async method
public async Task MyMethodAsync(CancellationToken cancellationToken = default(CancellationToken)) {
    cancellationToken.ThrowIfCancellationRequested();
    .... // some logic
}

// Task method
public Task MyMethodAsync(CancellationToken cancellationToken = default(CancellationToken)) {
    if(cancellationToken.IsCancellationRequested) {
        return Task.FromCanceled<object>(cancellationToken);
    }
    .... // some logic
}

// Precondition method with a tail
public Task MyMethodAsync(string name, CancellationToken cancellationToken = default(CancellationToken)) {
    if (path == null) {
        throw new ArgumentNullException(nameof(path));
    }
    if(cancellationToken.IsCancellationRequested) {
        return Task.FromCanceled<object>(cancellationToken);
    }
    return InternalMyMethodAsync(name, cancellationToken);
}

public Task InternalMyMethodAsync(string name, CancellationToken cancellationToken = default(CancellationToken)) {
    .... // some logic
}
```

The code from Microsoft uses the `ThrowIfCancellationRequested` [multiple times inside a method](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/File.cs#L987) but I don't think that this is necessary as we will have for each converted method this logic. If I am missing something, please correct me.

**Comment by hazzik** [comment]
Small design thoughts about interfaces and virtual/abstract methods. In case of overloading methods, the right decision would be to generate members as following:

1. If it is an interface, then generate only method with cancellation token. 
2. If this is an virtual or abstract method, then generate virtual or abstract method with cancellation token and sealed (non virtual method) which calls the virtual method with the default cancellation token (None).

**Comment by hazzik** [comment]
>The code from Microsoft uses the ThrowIfCancellationRequested multiple times inside a method 

In this case it's because `WriteLineAsync` does not accepts a token, so the invoking code needs to make a decision about cancelling.

**Comment by maca88** [comment]
> If it is an interface, then generate only method with cancellation token.

I will make this configurable, as for example Entity Framework Core is using one method with an optional cancellation token parameter through the whole project ([one example](https://github.com/aspnet/EntityFramework/blob/f386095005e46ea3aa4d677e4439cdac113dbfb1/src/EFCore.Relational/Storage/IRelationalCommand.cs#L65)).

> In this case it's because WriteLineAsync does not accepts a token, so the invoking code needs to make a decision about cancelling.

Good point! Shame on me that I didn't see that. :)

> Loops - same as above & insert check to loops (if there is no one accepts the token(?))

I think it is better to have an `Always` (I'm open to name suggestions) instead of `Loops` because it is not related only for loops but for every async invocation that does not accept a cancellation token.
For example:
```
public async Task DoSomethingAsync(CancellationToken cancellationToken) {
    cancellationToken.ThrowIfCancellationRequested(); // This would be generated with the Guard and Always option 
    //... some code
    cancellationToken.ThrowIfCancellationRequested(); // This would be generated with Always option
    await Task.Delay(200);
    //... some code
    cancellationToken.ThrowIfCancellationRequested(); // This would be generated with Always option
    await Task.Delay(200);
    //... some code
    for (var i = 0; i < 10; i++) {
        cancellationToken.ThrowIfCancellationRequested(); // This would be generated with Always option
        await Task.Delay(200);
    }
}
```
In my opinion, we should have `Always` instead of `Loops` and `(Loops)Verbose` that will do the same as Guard and in addition, will add a guard before each async invocation that does not accept a cancellation token.

**Comment by maca88** [comment]
> If it is an interface, then generate only method with cancellation token.
If this is an virtual or abstract method, then generate virtual or abstract method with cancellation token and a sealed (non virtual) method which calls the virtual method with the default cancellation token (None).

[Here](https://github.com/maca88/AsyncGenerator/blob/master/Source/AsyncGenerator.Tests/ExternalProjects/NHibernate/Fixture.cs#L37) is one example how you can now achieve the requested behavior.

> Probably the level of the cancellation guards shall be configurable

For now the guards can be configured with a boolean. If true, the guards will be inserted in the beginning of the method and before each async invocation that does not accept a cancellation token.

**Comment by hazzik** [comment]
Thanks!

**Comment by hazzik** [comment]
@maca88 there is a small issue. If method is implementing an interface so we do not need the overload without a cancellation token (implementors of IVersionType for example)

**Comment by maca88** [comment]
I will modify the `MethodGeneration` option to have the information which interfaces the method implements as the current IMethodSymbol parameter does not provide this information. Then we will be able to solve this issue.

**Comment by maca88** [comment]
I've replaced the `IMethodSymbol` parameter with `IMethodSymbolInfo` that contains also the implemented interfaces. Now to fix the problem just add an additional condition:
```
if (symbolInfo.ImplementedInterfaces.Any()) {
    return MethodCancellationToken.Parameter;
}
```
