### ISSUE TITLE
ToAsync method conversion of interfaces shall respect callForwarding option

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#31]
I'm trying to add following to the `methodConversion` of NHibernate project:
```
      - conversion: ToAsync
        containingType: NHibernate.Cache.ICache
        name: Get
      - conversion: ToAsync
        containingType: NHibernate.Cache.ICache
        name: Put
      - conversion: ToAsync
        containingType: NHibernate.Cache.ICache
        name: Remove
      - conversion: ToAsync
        containingType: NHibernate.Cache.ICache
        name: Clear
      - conversion: ToAsync
        containingType: NHibernate.Cache.ICache
        name: Lock
      - conversion: ToAsync
        containingType: NHibernate.Cache.ICache
        name: Unlock
```

I expect it to respect `callForwarding` option.  How do I do that?

**Comment by maca88** [comment]
When the `callForwarding` is set to `true` or `false` it shall apply to all converted methods. I tried to run the generator with the above conversions added and the `callForwarding` was correctly applied. For example, all converted methods of type `NHibernate.Cache.FakeCache` will forward the call as there is no async invocation inside them. 

But as you are referring to interfaces I don't know how should the `callForwarding` option affect them? Could you give an example of what do you want to achieve?

**Comment by hazzik** [comment]
> For example, all converted methods of type NHibernate.Cache.FakeCache will forward the call as there is no async invocation inside them.

I want to achieve exactly this, but instead the full methods were generated despite there were no async invocations inside. I'll double check in few hours.

**Comment by hazzik** [comment]
You're right. It works as expected.
