### ISSUE TITLE
Incorrect generation of methods which only throw NotImplementedException

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#4]
```
public void A()
{
	throw new NotImplementedException();
}
```
Is generated as following:
```
public Task A()
{
	try
	{
		return Task.FromException<object>(new NotImplementedException());
	}
	catch (Exception ex)
	{
		return Task.FromException<object>(ex);
	}
}
```

**Comment by maca88** [comment]
The same problem could apply also for `NotSupportedException` and other exceptions, so I think that we shall not wrap into a try/catch block when the first statement is a throw statement.

**Comment by hazzik** [comment]
Agree. The NotImplementedException was just an example. I was to lazy to write about other exceptions:)

**Comment by hazzik** [comment]
Shall it be just a throw or `return Task.FromException(...)`?

**Comment by maca88** [comment]
In my opinion we should apply the same idea as for guards/preconditions where we want to fail at the spot without the need to await the call. But after a quick look on the internet I found [this](http://stackoverflow.com/questions/13243975/suppress-warning-cs1998-this-async-method-lacks-await), where nobody mentioned the option to only throw the raw exception without wrapping it into a task. Currently I fixed this by throwing a raw exception but I will leave the issue open and do a deeper research about this.

**Comment by hazzik** [comment]
From [this](https://tryroslyn.azurewebsites.net/#b:master/f:r/K4Zwlgdg5gBAygTxAFwKYFsDcBYAUKSWRFDAOgBUALAJ1QEMATQiukAaxB1zwAdgAjADZgAxjBGDWIGAGEYAbzwxlMPkNExyrNjAAaARgCCIBBBEAKAJQKlKu8hoB7AO4wIqVwDlHyAJLoeQQxUCDQGAFEADxFUHmQwRwgrLjsAX1tlNWExVlMxLXY9ACZjPKsbXDt7J1d3Lx9/QODQ1Ajo2PjE5IyYVOUerI0CnV0AZlKzcsVcAEgZ2mRgaghNbVIAMWpHdCiYuISkuphvPwCg9BCw3Y6Dq0sUlXTcVKA==) it looks like 
```    public async Task X2Async() {
        throw new NotImplementedException();
    }```

Is really overcomplicated version of this:  

```    public Task X3Async() {
		return Task.FromException(new NotImplementedException());
    }```

**Comment by hazzik** [comment]
As far as I concern the 87643c8 has fixed this issue.
