### ISSUE TITLE
Generate async counterparts for overriden methods that have an async counterpart

### ISSUE THREAD

**Issue by maca88** [maca88/AsyncGenerator#46]
Example:
```
public abstract class ExternalClass
{
  public virtual bool Read()
  {
    SimpleFile.Read();
    return true;
  }

  public virtual async Task<bool> ReadAsync()
  {
    await SimpleFile.ReadAsync();
    return true;
  }
}

public class OverrideSyncMethod : ExternalClass
{
  public override bool Read()
  {
    base.Read();
    return false;
  }
}
```
Desired generated type:
```
public partial class OverrideSyncMethod : ExternalClass
{
  public override async Task<bool> ReadAsync()
  {
    await base.ReadAsync();
    return false;
  }
}
```
The only problem here is that in some cases the `OverrideSyncMethod` could intentionally override only the sync counterpart so the solution should support both scenarios.

**Comment by maca88** [comment]
In order to avoid too many settings the `ScanForMissingAsyncMembers` was used also for the async overrides.

**Comment by fredericDelaporte** [comment]
Ok, thanks,

So we have missed fixing manually one class, causing connection leaks to not be detected in async case (purpose of the debug connection provider).

When upgrading we should maybe remove the other manual fixes for letting that code be generated too.

**Comment by fredericDelaporte** [comment]
Testing it, it does not generate suitable code in all cases. In some cases it uses the sync base member instead of the async base member.

By example for `OnInitializeCollection` of `NHibernate.Test.Events.Collections.CollectionListeners.InitializeCollectionListener`, it generates:

```C#
public override Task OnInitializeCollectionAsync(InitializeCollectionEvent @event, CancellationToken cancellationToken)
{
	try
	{
		base.OnInitializeCollection(@event);
		AddEvent(@event, this);
		return Task.CompletedTask;
	}
	catch (System.Exception ex)
	{
		return Task.FromException<object>(ex);
	}
}
```

Instead of:
```C#
public override Task OnInitializeCollectionAsync(InitializeCollectionEvent @event, CancellationToken cancellationToken)
{
	var result = base.OnInitializeCollectionAsync(@event, cancellationToken);
	AddEvent(@event, this);
	return result;
}
```

`InsertOrderingFixture` and `QueryTimeoutTests` are affected too, but `DebugConnectionProvider` is correctly handled. It seems to be a trouble only with NHibernate defined async base methods.

**Comment by maca88** [comment]
The problem was that their method bodies weren't scanned, thanks for reporting it. Fixed and uploaded a new version.
By the way, your async method may behave different that the sync one as part of the code inside `base.OnInitializeCollectionAsync` method may be executed after the `AddEvent` call where this can never happen in the `OnInitializeCollection` method. So to assure that the async method behave exactly the same as the sync one the  `base.OnInitializeCollectionAsync` call must be awaited.

**Comment by fredericDelaporte** [comment]
Yes but for those cases code execution order is not significant.

**Comment by fredericDelaporte** [comment]
Works great now, thanks.
