### ISSUE TITLE
Missing member used by copied methods with NewType generation

### ISSUE THREAD

**Issue by fredericDelaporte** [maca88/AsyncGenerator#49]
When generating Async code as new type, constants/fields used by copied methods are not copied.

```C#
public class Class1
{
    public void Do()
    {
        DbConnection c = GetConnection();
        c.Open();
    }

    private const string _connectionString = "blah";

    private SqlConnection GetConnection() => new SqlConnection(_connectionString);
}
```

Get generated as:

```C#
public class Class1Async
{
    public Task DoAsync(CancellationToken cancellationToken = default(CancellationToken))
    {
        try
        {
            DbConnection c = GetConnection();
            return c.OpenAsync(cancellationToken);
        }
        catch (System.Exception ex)
        {
            return Task.FromException<object>(ex);
        }
    }

    private static SqlConnection GetConnection() => new SqlConnection(_connectionString);
}
```

Workaround: declare the field or constant as a property.
For this example, changing it to `private static string _connectionString => "blah";` dodge the trouble.

**Comment by maca88** [comment]
The problem was with the arrow method as the generator was not able to relate the field `_connectionString` to `GetConnection` method, causing the field not being generated as there was no relation to the any async member.
