### ISSUE TITLE
Add an option to ignore scanning for a method references

### ISSUE THREAD

**Issue by maca88** [maca88/AsyncGenerator#54]
As we've seen in this [issue](https://github.com/maca88/AsyncGenerator/issues/53), the method `SymbolFinder.FindReferencesAsync` can be quite expensive so we want to reduce its calls as far as possible. The idea here is to ignore the scanning for a method references even if the method conversion is set to `Smart` or `ToAsync`, this would be very useful for unit test methods as we know that they are not referenced by other methods.
By doing some local testing on the NHibernate test project I found out, that this will reduce the generation time by 20-25 seconds.

**Comment by maca88** [comment]
The option was [added](https://github.com/maca88/AsyncGenerator/commit/b3999a16d2dd7b2939e39ed798f9ead9f80a4f61) and also the NHibernate configuration was [altered](https://github.com/maca88/AsyncGenerator/commit/594926cb1dc83bc68629868faef6c34e8b604112) to speedup the geneartion time. The `NorthwindDbCreator` was completely ignored in order to avoid processing more than 3000 references to` IStatelessSession.Insert`. With the updated configuration the code is generated in 112 seconds (before 150 seconds) on my computer (Intel I7 860).

**Comment by fredericDelaporte** [comment]
Thanks for those optimizations, they are going to be merged. nhibernate/nhibernate-core#692
