### ISSUE TITLE
Ability to convert properties to async methods

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#6]
We, unfortunately, have some properties which can be detected as being convertible to async version. Yes, I know that it breaks the "semantic" of being a property, but anyway. Currently AsyncGenerator ignores all properties.

Here is a real life example from NHibernate:
```
//SessionImpl.cs
public override DbConnection Connection
{
	get { return connectionManager.GetConnection(); }
}
```
AsyncGenerator generates an async counterpart for `connectionManager.GetConnection()`, so the property itself becomes convertible to async method. Here is what I want to get:

```
public override DbConnection GetConnectionAsync()
{
	return connectionManager.GetConnectionAsync();
}
```

**Comment by maca88** [comment]
We shall add an option that will optionally convert properties to async, in addition to that we shall also scan for their usages and convert them. Example:
```
public void DoSomeWok()
{
	var conn = _session.Connection;
    ....
}
```
to
```
public async Task DoSomeWok()
{
	var conn = await _session.GetConnectionAsync();
    ....
}
```
It will require a little more effort, but I think that this would be the desired behavior.

**Comment by maca88** [comment]
I agree with you but here we need to be very carefully as this logic may cause some unwanted behaviors. Lets see an example:
Original code
```
public void MyMethod() {
    var stream = new MemoryStream();
    ....
    SubMethod();
    stream.Dispose();
}

public void SubMethod() { // An empty method that will be forced to be converted because of some inheritance dependency
}
```
Converted:
```
public async Task MyMethodAsync(CancellationToken cancellationToken = default(CancellationToken)) {
    cancellationToken.ThrowIfCancellationRequested();
    var stream = new MemoryStream();
    ....
    await SubMethodAsync(cancellationToken); // The original code supposed that this method would never throw
    stream.Dispose();
}

public Task SubMethodAsync(CancellationToken cancellationToken = default(CancellationToken)) {
    if(cancellationToken.IsCancellationRequested) {
        return Task.FromCanceled<string>(cancellationToken); // If we got here then the stream that was allocated will never be disposed!
    }
    return Task.CompletedTask;
}
```
I know that the above example is an example of a badly written code but we still need to consider this case.

So let see how this logic shall be implemented for various cases (inspired by Microsoft [here](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/File.cs#L946) and [here](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/File.cs#L973)):
```
// Async method
public async Task MyMethodAsync(CancellationToken cancellationToken = default(CancellationToken)) {
    cancellationToken.ThrowIfCancellationRequested();
    .... // some logic
}

// Task method
public Task MyMethodAsync(CancellationToken cancellationToken = default(CancellationToken)) {
    if(cancellationToken.IsCancellationRequested) {
        return Task.FromCanceled<object>(cancellationToken);
    }
    .... // some logic
}

// Precondition method with a tail
public Task MyMethodAsync(string name, CancellationToken cancellationToken = default(CancellationToken)) {
    if (path == null) {
        throw new ArgumentNullException(nameof(path));
    }
    if(cancellationToken.IsCancellationRequested) {
        return Task.FromCanceled<object>(cancellationToken);
    }
    return InternalMyMethodAsync(name, cancellationToken);
}

public Task InternalMyMethodAsync(string name, CancellationToken cancellationToken = default(CancellationToken)) {
    .... // some logic
}
```

The code from Microsoft uses the `ThrowIfCancellationRequested` [multiple times inside a method](https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/src/System/IO/File.cs#L987) but I don't think that this is necessary as we will have for each converted method this logic. If I am missing something, please correct me.

**Comment by maca88** [comment]
Support [added](https://github.com/maca88/AsyncGenerator/commit/0c536b18105448434c7fd544896f2c09423c5e96). The feature can be enabled by setting the [PropertyConversion](https://github.com/maca88/AsyncGenerator/blob/master/Source/AsyncGenerator.Core/Configuration/IFluentProjectAnalyzeConfiguration.cs#L22) to `true`. (example in [yaml](https://github.com/maca88/AsyncGenerator/blob/master/Source/AsyncGenerator.Tests/ExternalProjects/NHibernate/Configuration.yaml#L119)).

As property accessors are methods their conversion can be changed the same way as for normal methods. Example in yaml (ignoring getter of `MyProperty` property):
```
- conversion: Ignore
    name: get_MyProperty
    containingTypeName: MyClass
```
