### ISSUE TITLE
ConfigureMSBuild throws PlatformNotSupported exception on non Windows platforms

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#60]

**Comment by maca88** [comment]
This will be addressed with #61.

**Comment by hazzik** [comment]
@maca88 can we have a version which runs on mono (I don't really care about the dotnetcore yet)?

**Comment by maca88** [comment]
I've made a [PR for mono](https://github.com/maca88/AsyncGenerator/pull/65). For running on mono, we need the preview packages of `Microsoft.Build` `15.5`. There are some failing tests that needs to be fixed. I've tried to run the generator for NHibernate on Ubuntu and it worked only for the `NHibernate` and `NHibernate.DomainModel` projects. For the test project, something went wrong when searching for missing members.
