### ISSUE TITLE
Bound error on ParallelFor conversion

### ISSUE THREAD

**Issue by fredericDelaporte** [maca88/AsyncGenerator#72]
`ParallelFor(1, 100, ...)` is converted to `Task.WhenAll(Enumerable.Range(1, 100)...` while it should be `Task.WhenAll(Enumerable.Range(1, 99)`. (#63)

`ParallelFor` semantic is "first included last excluded", while `Range` semantic is "first included, total count".
So if we have `ParallelFor(a, b, ...)`, the conversion should yield `Task.WhenAll(Enumerable.Range(a, b - a)...`.

This was spotted with nhibernate/nhibernate-core#1455 test.

**Comment by maca88** [comment]
Thanks for the report, I completely forgot about this.
