### ISSUE TITLE
Doesn't work after VS 2017 upgraded to 15.5

### ISSUE THREAD

**Issue by bahusoid** [maca88/AsyncGenerator#74]
` [exec] 06:53:11,766 FATAL Program:0 - System.InvalidOperationException: Visual Studio installation directory was not found. Install Visual Studio or set the environment variable VSINSTALLDIR`

And after setting VSINSTALLDIR variable as suggested to: 
 C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE

I got the following:
```
 [exec] 07:17:06,651 INFO  Program:0 - AsyncGenerator
     [exec]
     [exec] 07:17:06,933 INFO  AsyncCodeGenerator:0 - Generating async code started
     [exec] 07:17:07,478 INFO  AsyncCodeGenerator:0 - Opening project 'C:\Sources\Git\nhibernate-core\src\NHibernate\NHibernate.csproj' started
     [exec] 07:17:08,041 FATAL Program:0 - System.InvalidOperationException: One or more errors occurred while opening the project:
     [exec] Msbuild failed when processing the file 'C:\Sources\Git\nhibernate-core\src\NHibernate\NHibernate.csproj' with message: The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Sources\Git\nhibernate-core\src\NHibernate\NHibernate.csproj
     [exec] Hint: For suppressing irrelevant errors use SuppressDiagnosticFailures option.
     [exec]    at AsyncGenerator.AsyncCodeGenerator.CheckForErrors(MSBuildWorkspace workspace, String itemType, ImmutableArray`1 supressFailuresPredicates)
     [exec]    at AsyncGenerator.AsyncCodeGenerator.<OpenProject>d__9.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at AsyncGenerator.AsyncCodeGenerator.<GenerateAsync>d__1.MoveNext()
     [exec] --- End of stack trace from previous location where exception was thrown ---
     [exec]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     [exec]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     [exec]    at AsyncGenerator.CommandLine.Program.Main(String[] args)

```
I can build NHibernate solution no problem both inside VS and via ShowBuildMenu.bat

**Comment by bahusoid** [comment]
Might be faulty upgrade. "Devoloper Command Propmt For VS 2017" also  doesn't work. But VS 2017 repair did not help

**Comment by hazzik** [comment]
Do you have .net core tools installed in VS 2017? What about .net core sdk (standalone)?

**Comment by bahusoid** [comment]
".NET Core 2.0 development tools" is ticked in installer. Also I see the following installed:

![netcoreinstalled](https://user-images.githubusercontent.com/22025304/33647484-41d8232e-da7b-11e7-8ca5-5f3aaa28acb1.png)

`dotnet ` and 'dotnet msbuld' commands work in console (not sure if it's related to .net core tools)

**Comment by fredericDelaporte** [comment]
I have just upgrade to 15.5, no troubles on my box. I do not have any Core preview, only full versions.
![core](https://user-images.githubusercontent.com/12201973/33658813-43dbf47c-da7e-11e7-832b-61fb6a31515a.png)

**Comment by bahusoid** [comment]
Yep. Seems like upgrade in unlucky day issue. Full reinstalling helped...

**Comment by maca88** [comment]
Strange, for some reason [MSBuildLocator](https://github.com/Microsoft/MSBuildLocator) that is used for locating the Visual Studio installation folder didn't found anything.

> And after setting VSINSTALLDIR variable as suggested to:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE

The `VSINSTALLDIR` variable that is set on my machine [prior the generation process](https://github.com/maca88/AsyncGenerator/blob/master/Source/AsyncGenerator/Internal/EnvironmentHelper.cs#L56) is:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community`
