### ISSUE TITLE
Redefine the try/catch wrapping rules

### ISSUE THREAD

**Issue by maca88** [maca88/AsyncGenerator#83]
The goal of this issue is to define better the rules when the body of a synchronous method that returns a `Task` should be wrapped into a `try`/`catch` block.
Currently, the generator do the wrapping when one of the following rules applies:
- there is more than one statement
- there is one statement that has zero or more than one invocations
- there is one statement that has one invocation that do not return a `Task`

The problem with the current rules is that the wrapping is made also when is not needed:
[NH example](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate.Test/Async/NHSpecificTest/NH372/Fixture.cs#L57)
[NH example](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate.Test/Async/Tools/hbm2ddl/SchemaUpdate/MigrationFixture.cs#L63)

There is also a [recent bug](https://github.com/maca88/AsyncGenerator/commit/31ef8b3a22038238f1f4736634115b974428e26c#commitcomment-27147943) reported by @hazzik

Also, by looking at Microsoft code for `SqlDataReader` class, they [do not wrap](http://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/SqlDataReader.cs,4258) [certain exceptions](http://referencesource.microsoft.com/#System.Data.DataSetExtensions/System/Data/DataSetUtil.cs,122) into a task, but instead they just throws them right away.

If we take the rule from Microsoft that `NullReferenceException` shouldn't be wrapped and the recent reported bug into consideration, then we can redefine the current rules to wrap the method body when one of the following rules applies:
- there is at least one element access expression e.g. `return list[10];`
- there is at least one cast expression e.g. `return (int)longValue;`
- there is more than one invocation expression e.g. `return ReadAsync(GetFilePath());`
- there is one invocation expression that do not return a `Task` e.g. `return GetFilePath()`

[Here are the changes](https://github.com/maca88/nhibernate-core/commit/527372266a89048de2c64aff2530332105c429a1) for NHibernate, when the new rules are applied. 

We should consider if we want to have also the following rule:
- there is at least one object creation expression that has at least one argument e.g. `new MemoryStream(null);`

@hazzik, @fredericDelaporte what are your thoughts about it, what rules would you apply?

**Comment by maca88** [comment]
> But I think the fourth rule should be amended for considering property access as invocations. Property access may throw, and such throws may be something else than pre-condition failures, isn't it?

I firstly tried to consider them, but there were a lot of false positives, for example:
- access an auto property
- acces an external property that never throws `typeof(Test).FullName`, `Date.Now` ...

So instead of just detecting property accesses, I've added the following rule for wrapping into a try/catch block:
- there is at least one internal property accessed that is not an auto property e.g. `public bool IsValid => Validate();`

I excluded external properties, as it is not possible to detect whether they are auto properties or not. 
Unfortunately, the rule will detect an interface property as an auto property, but the implementation may not be an auto property. Here we have to decide whether wrap interface/abstract property accesses or not, if we want to consider properties.

[Here are the changes](https://github.com/maca88/nhibernate-core/commit/37604ff4cc710c9033cc0aa8eeb4e26190311548) when the property rule is added to the previuos four rules. From the changes we can see that there are still false positives e.g. [example](https://github.com/maca88/nhibernate-core/commit/37604ff4cc710c9033cc0aa8eeb4e26190311548#diff-337b319856bce8000b88cdb60f648d48R53) where [EntityName property](https://github.com/nhibernate/nhibernate-core/blob/ad4c2ef101cbf8ba798220973f4f78dd795e0896/src/NHibernate/Event/SaveOrUpdateEvent.cs#L49) only returns a field.

From my experience most of the properties are either auto properties or they are returning a field, so I am not sure if is a good idea to include them, when also considering that the rule has its own limitations.

**Comment by fredericDelaporte** [comment]
I would favor having false positives rather than having missed ones.

> From my experience most of the properties are either auto properties or they are returning a field, so I am not sure if is a good idea to include them, when also considering that the rule has its own limitations.

It depends on the code. Maybe wrapping on property calls should then be an option. Why not still optimize it on auto-property cases (but not interface ones)? About external cases, if willing to allow ignoring them, that should then be yet another option I think.

**Comment by maca88** [comment]
I've added [an option](https://github.com/maca88/AsyncGenerator/pull/84/commits/3464ad7e6c8223b87e908ec0e204e74e4c2df05d#diff-755dbcc2436f0927a9728561d582c21dR17) for conditionally wrapping property getter calls, which can be used also for external ones. By default getter calls are not wrapped as from [the recommendation](https://stackoverflow.com/a/1488488), getters should be safe to call. Setters are always wrapped except when they are auto-properties that are not virtual/abstract or interface ones.

[This are the changes](https://github.com/maca88/nhibernate-core/commit/b6939e250c5d80afe6459d673ae504b1027ccbb3) for the NHibernate when the new option is used for wrapping property getter calls. If you agree with the changes I will release a new version.

**Comment by fredericDelaporte** [comment]
I am agree with them.
