### ISSUE TITLE
Just call an sync version of a method if nothing inside is async

### ISSUE THREAD

**Issue by hazzik** [maca88/AsyncGenerator#9]
If a method is marked as to be generated (mostly implicitly as an implementation of an interface, or by any other means) and does not call any async methods itself then it shall be generated as an async wrapper of a sync version counterpart.

Example: https://github.com/hazzik/nhibernate-core/blob/66a2bf948c82900d9948a52297ca79a65ec248f0/src/NHibernate/Async/Event/Default/OnUpdateVisitor.cs#L28

**Comment by maca88** [comment]
I will make an option to have this configurable

**Comment by maca88** [comment]
Now is possible to forward the call using the `CallForwarding` option, using a boolean or a predicate for fine tuning.

**Comment by hazzik** [comment]
Thanks
