### ISSUE TITLE
Diagnostics doesn't work for anonymous functions

### ISSUE THREAD

**Issue by maca88** [maca88/AsyncGenerator#99]
Example:
```
public void Enumerable()
{
  var enumerable = System.Linq.Enumerable.Range(1, 10)
    .Select(o => SimpleFile.Write(o.ToString()));
}
```
a warning should be printed that SimpleFile.Write has an async counterpart but couldn't be used, but it isn't.

**Comment by hazzik** [comment]
I was thinking about a warning in the generated file itself. Not in the
logs.

**Comment by maca88** [comment]
My bad, I misread your comment. Where did you think that the warnings should be located? 

If we take the [Enumerable test method](https://github.com/maca88/AsyncGenerator/blob/master/Source/AsyncGenerator.Tests/Diagnostics/Input/EnumerableWarning.cs#L13) as an example, the following warnings gets printed:
```
Diagnostics for document: Diagnostics\Input\EnumerableWarning.cs
Method Enumerable (13,3)-(18,4) ignored reason: Never used and has no async invocations
Function  (16,12)-(16,37) ignored reason: Cascade ignored
Method reference Write (16,28)-(16,33) ignored reason: Method is copied
Method reference Write (16,28)-(16,33): Has an async counterpart that could't been used
Function  (17,13)-(17,48) ignored reason: Cascade ignored
Method reference Write (17,29)-(17,34) ignored reason: Method is copied
Method reference Write (17,29)-(17,34): Has an async counterpart that could't been used
``` 

The current diagnostics logic works like this:
1. For each method reference that is ignored check if there is an async counterpart
2. If there is:
  - Mark the method reference (e.g. `SimpleFile.Write("")`) with a warning: Has an async counterpart that could't been used
  - Mark the function (e.g. `o => SimpleFile.Write("")`) that contains the method reference with a warning, in order to see its ignored reason (useless in this example)
  - If the method that contains the function is ignored, mark it with a warning in order to see what was the reason
  
For this example we cannot print the warning where the method reference or function or method is as it won't be generated. The only way that I see is to print the warnings at the beginning of the file, which in this case would contain just the warnings.
